image: node:8.0.0

before_script:
  - yarn

stages:
  - deployExtension

deployExtension:
  stage: deployExtension
  only:
    - master
  script:
    - mv -v yarn.lock .yarn.lock
    - mv -v package.json .package.json
    - mv -v README.md .README.md
    - mv -v LICENSE .LICENSE
    - mv -v TODO .TODO
    - mv -v 'Privacy Policy' .privacypolicy
    - node ./.deploytoAMO.js firefox .

# If file name  starts with a dot, web-ext won't package them into the extension
# The --ignore-files option added inside .firefoxdeploy.js does not work for some reason - raised an issue in mozilla web-ext -> https://github.com/mozilla/web-ext/issues/1333
# Once that is resolved, we can remove the 'mv' commands above